### ISSUE TITLE
Protocol testnet release and testing

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#23]
Tracking the high level task for protocol testing on the testnet. Prior to main net launch we'd like to be confident that the protocol will run continuously without deadlocking or locking funds, and ensure that the base economic design is implemented correctly and value flows through the protocol as intended.

- [x] Deploy on internal testnet
- [x] Deploy on public Ethereum testnets
- [x] Integration testing with Go and JS clients
- [x] User acceptance testing on Ethereum testnet
