### ISSUE TITLE
Ethereum main net Snowmelt Release

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#24]
High level task to track releasing version 1 of the Livepeer protocol on the Ethereum main network. 

- [x] Smart contract deployments
- [x] Genesis state setup
- [x] Start the protocol
- [x] Delegation game period
- [x] Activate round progression
