### ISSUE TITLE
Client reference implementation for Snowmelt version of protocol

### ISSUE THREAD

**Issue by dob** [livepeer/project-management#25]
Tracking the high level task of completing a reference implementation of the go-livepeer client so that users can interact with the protocol at launch. This should allow users to:

- [x] Invoke all protocol transactions as a delegator - bonding, unbonding, withdrawing, claiming fees
- [x] Invoke all protocol transactions as a broadcaster - deposit, job
- [x] Invoke all protocol transacations as a transcoder - candidacy, claiming/proving work, distributing fees, calling reward
- [ ] Invoke all protocol actions as a watcher - slashing

A transcoder should be able to keep this node running 24/7 and it will handle all of the actions to ensure that they act honestly and don't get slashed.
